export interface CountryPreset {
  name: string;
  code: string;
  flag: string;
  timezone: string;
  defaultWorkingDays: string[];
  defaultStartTime: string;
  defaultEndTime: string;
  defaultBreakStart: string;
  defaultBreakEnd: string;
  defaultSlotDuration: number;
  defaultEducationSystem: string;
  defaultGradingSystem: string;
  defaultSemesterSystem: string;
  defaultInstitutionType: string;
}

export const countries: CountryPreset[] = [
  {
    name: "Sénégal",
    code: "SN",
    flag: "🇸🇳",
    timezone: "Africa/Dakar",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "18:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:30",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "France",
    code: "FR",
    flag: "🇫🇷",
    timezone: "Europe/Paris",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "18:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    flag: "🇨🇮",
    timezone: "Africa/Abidjan",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:30",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Cameroun",
    code: "CM",
    flag: "🇨🇲",
    timezone: "Africa/Douala",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:30",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Mali",
    code: "ML",
    flag: "🇲🇱",
    timezone: "Africa/Bamako",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    flag: "🇧🇫",
    timezone: "Africa/Ouagadougou",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Gabon",
    code: "GA",
    flag: "🇬🇦",
    timezone: "Africa/Libreville",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Congo",
    code: "CG",
    flag: "🇨🇬",
    timezone: "Africa/Brazzaville",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Togo",
    code: "TG",
    flag: "🇹🇬",
    timezone: "Africa/Lome",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Bénin",
    code: "BJ",
    flag: "🇧🇯",
    timezone: "Africa/Porto-Novo",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Niger",
    code: "NE",
    flag: "🇳🇪",
    timezone: "Africa/Niamey",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "07:30",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Guinée",
    code: "GN",
    flag: "🇬🇳",
    timezone: "Africa/Conakry",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "17:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Maroc",
    code: "MA",
    flag: "🇲🇦",
    timezone: "Africa/Casablanca",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "18:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Tunisie",
    code: "TN",
    flag: "🇹🇳",
    timezone: "Africa/Tunis",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "18:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "États-Unis",
    code: "US",
    flag: "🇺🇸",
    timezone: "America/New_York",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "16:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "13:00",
    defaultSlotDuration: 60,
    defaultEducationSystem: "anglo-saxon",
    defaultGradingSystem: "A-F",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Canada",
    code: "CA",
    flag: "🇨🇦",
    timezone: "America/Toronto",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "16:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "13:00",
    defaultSlotDuration: 60,
    defaultEducationSystem: "anglo-saxon",
    defaultGradingSystem: "A-F",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Belgique",
    code: "BE",
    flag: "🇧🇪",
    timezone: "Europe/Brussels",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "18:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
  {
    name: "Suisse",
    code: "CH",
    flag: "🇨🇭",
    timezone: "Europe/Zurich",
    defaultWorkingDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
    defaultStartTime: "08:00",
    defaultEndTime: "18:00",
    defaultBreakStart: "12:00",
    defaultBreakEnd: "14:00",
    defaultSlotDuration: 90,
    defaultEducationSystem: "LMD",
    defaultGradingSystem: "20",
    defaultSemesterSystem: "semestriel",
    defaultInstitutionType: "universite",
  },
];

export function getCountryByCode(code: string): CountryPreset | undefined {
  return countries.find((c) => c.code === code);
}

export const institutionTypes = [
  { value: "universite", label: "Université" },
  { value: "lycee", label: "Lycée" },
  { value: "college", label: "Collège" },
  { value: "ecole_primaire", label: "École primaire" },
  { value: "autre", label: "Autre" },
];

export const educationSystems = [
  { value: "LMD", label: "LMD (Licence-Master-Doctorat)" },
  { value: "classique", label: "Classique" },
  { value: "anglo-saxon", label: "Anglo-saxon" },
  { value: "autre", label: "Autre" },
];

export const gradingSystems = [
  { value: "20", label: "Sur 20" },
  { value: "100", label: "Sur 100" },
  { value: "A-F", label: "A-F (américain)" },
  { value: "autre", label: "Autre" },
];

export const semesterSystems = [
  { value: "semestriel", label: "Semestriel" },
  { value: "trimestriel", label: "Trimestriel" },
  { value: "annuel", label: "Annuel" },
];

export const roomTypes = [
  { value: "amphi", label: "Amphithéâtre" },
  { value: "salle_td", label: "Salle de TD" },
  { value: "labo", label: "Laboratoire" },
  { value: "salle_info", label: "Salle informatique" },
  { value: "salle_normale", label: "Salle normale" },
];

export const subjectTypes = [
  { value: "cours", label: "Cours magistral" },
  { value: "td", label: "Travaux dirigés" },
  { value: "tp", label: "Travaux pratiques" },
  { value: "projet", label: "Projet" },
];

export const dayNames: Record<number, string> = {
  1: "Lundi",
  2: "Mardi",
  3: "Mercredi",
  4: "Jeudi",
  5: "Vendredi",
  6: "Samedi",
  7: "Dimanche",
};

export const subjectColors = [
  "#10b981", "#f59e0b", "#ef4444", "#8b5cf6", "#ec4899",
  "#06b6d4", "#f97316", "#84cc16", "#6366f1", "#14b8a6",
  "#e11d48", "#7c3aed", "#0ea5e9", "#d946ef", "#22c55e",
];
